version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sql-runner-backend
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=your-secret-key-change-in-production-123456789
      - DATABASE_PATH=/app/sql_runner.db
    volumes:
      - ./backend/sql_runner.db:/app/sql_runner.db
    networks:
      - sql-runner-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sql-runner-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - sql-runner-network

networks:
  sql-runner-network:
    driver: bridge

volumes:
  db-data: